### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by anncwb** [santicros/vue3-vite-typescript-jest#1]
My node version is 12.16.1. You will get an error when running your project. Error message

```
 FAIL  src/components/Greeting.spec.ts
  ● Test suite failed to run

    TypeError: tr.configsFor is not a function

      at getTsJestConfig (node_modules/vue-jest/lib/utils.js:69:24)

 FAIL  src/App.spec.ts
  ● Test suite failed to run

    TypeError: tr.configsFor is not a function

      at getTsJestConfig (node_modules/vue-jest/lib/utils.js:69:24)
```

**Comment by santicros** [comment]
Interesting. I can't seem to reproduce it. I've downloaded node 12.16.1 and tried with the blank starter with npm or yarn and did work for me. Just had to `npm install` and `npm run test:unit`. Can you check on your package-lock or yarn.lock that vue-jest is in alpha.5 version?

Still it's possible that is a bug with vue-jest, as the version that works with Vue3 is still in alpha stage.

**Comment by anncwb** [comment]
I use your project for testing. It may be that you installed a certain dependency globally, but I did not install it.

**Comment by anncwb** [comment]
I use window10 to test the same error
![image](https://user-images.githubusercontent.com/28132598/97151303-4c7be800-17aa-11eb-9a22-e239c04499e2.png)

**Comment by santicros** [comment]
Hi @anncwb thanks for trying it again.

It seems to me it's a bug with vue-jest (though can't understand what has changed in our environments). Could you please open an issue at vue-jest (https://github.com/vuejs/vue-jest)? I think they'll know what to look for.

Thanks!!
